// Generated by generate-icons.mjs from lucide (ISC license), the icon set used on web and desktop.
// Do not edit by hand.
enum Lucide: String, CaseIterable {
    case archive = "archive"
    case archiveRestore = "archive-restore"
    case arrowDownToLine = "arrow-down-to-line"
    case arrowLeft = "arrow-left"
    case arrowUpFromLine = "arrow-up-from-line"
    case bell = "bell"
    case check = "check"
    case chevronDown = "chevron-down"
    case chevronLeft = "chevron-left"
    case chevronRight = "chevron-right"
    case circleAlert = "circle-alert"
    case circleCheck = "circle-check"
    case clock = "clock"
    case clock3 = "clock-3"
    case cloud = "cloud"
    case cloudUpload = "cloud-upload"
    case download = "download"
    case ellipsis = "ellipsis"
    case eye = "eye"
    case eyeOff = "eye-off"
    case file = "file"
    case fileImage = "file-image"
    case fileText = "file-text"
    case folder = "folder"
    case folderInput = "folder-input"
    case folderPlus = "folder-plus"
    case folderUp = "folder-up"
    case hardDrive = "hard-drive"
    case inbox = "inbox"
    case info = "info"
    case laptop = "laptop"
    case layoutGrid = "layout-grid"
    case list = "list"
    case loaderCircle = "loader-circle"
    case lock = "lock"
    case logOut = "log-out"
    case menu = "menu"
    case minus = "minus"
    case monitor = "monitor"
    case moon = "moon"
    case pause = "pause"
    case pencil = "pencil"
    case play = "play"
    case plus = "plus"
    case refreshCw = "refresh-cw"
    case rotateCcw = "rotate-ccw"
    case search = "search"
    case send = "send"
    case settings = "settings"
    case share2 = "share-2"
    case shieldCheck = "shield-check"
    case smartphone = "smartphone"
    case star = "star"
    case sun = "sun"
    case trash = "trash"
    case triangleAlert = "triangle-alert"
    case users = "users"
    case wifiOff = "wifi-off"
    case x = "x"

    /// SVG path data in lucide's 24×24 coordinate space, drawn with a 2-unit round stroke.
    var paths: [String] {
        switch self {
        case .archive: return ["M3 3h18a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-18a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1z", "M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8", "M10 12h4"]
        case .archiveRestore: return ["M3 3h18a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-18a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1z", "M4 8v11a2 2 0 0 0 2 2h2", "M20 8v11a2 2 0 0 1-2 2h-2", "m9 15 3-3 3 3", "M12 12v9"]
        case .arrowDownToLine: return ["M12 17V3", "m6 11 6 6 6-6", "M19 21H5"]
        case .arrowLeft: return ["m12 19-7-7 7-7", "M19 12H5"]
        case .arrowUpFromLine: return ["m18 9-6-6-6 6", "M12 3v14", "M5 21h14"]
        case .bell: return ["M10.268 21a2 2 0 0 0 3.464 0", "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"]
        case .check: return ["M20 6 9 17l-5-5"]
        case .chevronDown: return ["m6 9 6 6 6-6"]
        case .chevronLeft: return ["m15 18-6-6 6-6"]
        case .chevronRight: return ["m9 18 6-6-6-6"]
        case .circleAlert: return ["M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0z", "M12 8L12 12", "M12 16L12.01 16"]
        case .circleCheck: return ["M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0z", "m16 9-5.5 5.5L8 12"]
        case .clock: return ["M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0z", "M12 6v6l4 2"]
        case .clock3: return ["M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0z", "M12 6v6h4"]
        case .cloud: return ["M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"]
        case .cloudUpload: return ["M12 13v8", "M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242", "m8 17 4-4 4 4"]
        case .download: return ["M12 15V3", "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4", "m7 10 5 5 5-5"]
        case .ellipsis: return ["M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0z", "M18 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0z", "M4 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0z"]
        case .eye: return ["M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0", "M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0z"]
        case .eyeOff: return ["M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49", "M14.084 14.158a3 3 0 0 1-4.242-4.242", "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143", "m2 2 20 20"]
        case .file: return ["M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z", "M14 2v5a1 1 0 0 0 1 1h5"]
        case .fileImage: return ["M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z", "M14 2v5a1 1 0 0 0 1 1h5", "M8 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z", "m20 17-1.296-1.296a2.41 2.41 0 0 0-3.408 0L9 22"]
        case .fileText: return ["M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z", "M14 2v5a1 1 0 0 0 1 1h5", "M10 9H8", "M16 13H8", "M16 17H8"]
        case .folder: return ["M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"]
        case .folderInput: return ["M2 9V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-1", "M2 13h10", "m9 16 3-3-3-3"]
        case .folderPlus: return ["M12 10v6", "M9 13h6", "M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"]
        case .folderUp: return ["M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z", "M12 10v6", "m9 13 3-3 3 3"]
        case .hardDrive: return ["M10 16h.01", "M2.212 11.577a2 2 0 0 0-.212.896V18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5.527a2 2 0 0 0-.212-.896L18.55 5.11A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z", "M21.946 12.013H2.054", "M6 16h.01"]
        case .inbox: return ["M22 12 16 12 14 15 10 15 8 12 2 12", "M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"]
        case .info: return ["M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0z", "M12 16v-4", "M12 8h.01"]
        case .laptop: return ["M18 5a2 2 0 0 1 2 2v8.526a2 2 0 0 0 .212.897l1.068 2.127a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45l1.068-2.127A2 2 0 0 0 4 15.526V7a2 2 0 0 1 2-2z", "M20.054 15.987H3.946"]
        case .layoutGrid: return ["M4 3h5a1 1 0 0 1 1 1v5a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-5a1 1 0 0 1 1 -1z", "M15 3h5a1 1 0 0 1 1 1v5a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-5a1 1 0 0 1 1 -1z", "M15 14h5a1 1 0 0 1 1 1v5a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-5a1 1 0 0 1 1 -1z", "M4 14h5a1 1 0 0 1 1 1v5a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1v-5a1 1 0 0 1 1 -1z"]
        case .list: return ["M3 5h.01", "M3 12h.01", "M3 19h.01", "M8 5h13", "M8 12h13", "M8 19h13"]
        case .loaderCircle: return ["M21 12a9 9 0 1 1-6.219-8.56"]
        case .lock: return ["M5 11h14a2 2 0 0 1 2 2v7a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-7a2 2 0 0 1 2 -2z", "M7 11V7a5 5 0 0 1 10 0v4"]
        case .logOut: return ["m16 17 5-5-5-5", "M21 12H9", "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"]
        case .menu: return ["M4 5h16", "M4 12h16", "M4 19h16"]
        case .minus: return ["M5 12h14"]
        case .monitor: return ["M4 3h16a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2z", "M8 21L16 21", "M12 17L12 21"]
        case .moon: return ["M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"]
        case .pause: return ["M15 3h3a1 1 0 0 1 1 1v16a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-16a1 1 0 0 1 1 -1z", "M6 3h3a1 1 0 0 1 1 1v16a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-16a1 1 0 0 1 1 -1z"]
        case .pencil: return ["M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z", "m15 5 4 4"]
        case .play: return ["M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"]
        case .plus: return ["M5 12h14", "M12 5v14"]
        case .refreshCw: return ["M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8", "M21 3v5h-5", "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16", "M8 16H3v5"]
        case .rotateCcw: return ["M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8", "M3 3v5h5"]
        case .search: return ["m21 21-4.34-4.34", "M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0z"]
        case .send: return ["M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z", "m21.854 2.147-10.94 10.939"]
        case .settings: return ["M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915", "M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0z"]
        case .share2: return ["M15 5a3 3 0 1 0 6 0a3 3 0 1 0 -6 0z", "M3 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0z", "M15 19a3 3 0 1 0 6 0a3 3 0 1 0 -6 0z", "M8.59 13.51L15.42 17.49", "M15.41 6.51L8.59 10.49"]
        case .shieldCheck: return ["M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z", "m9 12 2 2 4-4"]
        case .smartphone: return ["M7 2h10a2 2 0 0 1 2 2v16a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-16a2 2 0 0 1 2 -2z", "M12 18h.01"]
        case .star: return ["M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"]
        case .sun: return ["M8 12a4 4 0 1 0 8 0a4 4 0 1 0 -8 0z", "M12 2v2", "M12 20v2", "m4.93 4.93 1.41 1.41", "m17.66 17.66 1.41 1.41", "M2 12h2", "M20 12h2", "m6.34 17.66-1.41 1.41", "m19.07 4.93-1.41 1.41"]
        case .trash: return ["M10 11v6", "M14 11v6", "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6", "M3 6h18", "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"]
        case .triangleAlert: return ["m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3", "M12 9v4", "M12 17h.01"]
        case .users: return ["M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2", "M16 3.128a4 4 0 0 1 0 7.744", "M22 21v-2a4 4 0 0 0-3-3.87", "M5 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0z"]
        case .wifiOff: return ["M12 20h.01", "M8.5 16.429a5 5 0 0 1 7 0", "M5 12.859a10 10 0 0 1 5.17-2.69", "M19 12.859a10 10 0 0 0-2.007-1.523", "M2 8.82a15 15 0 0 1 4.177-2.643", "M22 8.82a15 15 0 0 0-11.288-3.764", "m2 2 20 20"]
        case .x: return ["M18 6 6 18", "m6 6 12 12"]
        }
    }
}
