/* global console */
// Regenerates Harbor0/Lucide.swift from the lucide icons the web and desktop apps use.
// Run from the repository root: node apps/ios/generate-icons.mjs
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const icons = [
  'archive', 'archive-restore', 'arrow-down-to-line', 'arrow-left', 'arrow-up-from-line', 'bell', 'check',
  'chevron-down', 'chevron-left', 'chevron-right', 'circle-alert', 'circle-check', 'clock', 'clock-3', 'cloud',
  'cloud-upload', 'download', 'ellipsis', 'eye', 'eye-off', 'file', 'file-image', 'file-text', 'folder',
  'folder-input', 'folder-plus', 'folder-up', 'hard-drive', 'inbox', 'info', 'laptop', 'layout-grid', 'list',
  'loader-circle', 'lock', 'log-out', 'menu', 'minus', 'monitor', 'moon', 'pause', 'pencil', 'play', 'plus',
  'refresh-cw', 'rotate-ccw', 'search', 'send', 'settings', 'share-2', 'shield-check', 'smartphone', 'star', 'sun',
  'trash', 'triangle-alert', 'users', 'wifi-off', 'x',
];
const n = (value) => Number(value ?? 0);
const shapes = {
  path: (a) => a.d,
  line: (a) => `M${a.x1} ${a.y1}L${a.x2} ${a.y2}`,
  polyline: (a) => `M${a.points}`,
  polygon: (a) => `M${a.points}z`,
  circle: (a) => {
    const r = n(a.r);
    return `M${n(a.cx) - r} ${a.cy}a${r} ${r} 0 1 0 ${2 * r} 0a${r} ${r} 0 1 0 ${-2 * r} 0z`;
  },
  ellipse: (a) =>
    `M${n(a.cx) - n(a.rx)} ${a.cy}a${a.rx} ${a.ry} 0 1 0 ${2 * n(a.rx)} 0a${a.rx} ${a.ry} 0 1 0 ${-2 * n(a.rx)} 0z`,
  rect: (a) => {
    const [x, y, w, h] = [n(a.x), n(a.y), n(a.width), n(a.height)];
    const r = Math.min(n(a.rx ?? a.ry), w / 2, h / 2);
    if (!r) return `M${x} ${y}h${w}v${h}h${-w}z`;
    return `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}v${h - 2 * r}a${r} ${r} 0 0 1 ${-r} ${r}h${2 * r - w}a${r} ${r} 0 0 1 ${-r} ${-r}v${2 * r - h}a${r} ${r} 0 0 1 ${r} ${-r}z`;
  },
};
const camel = (name) => name.replace(/-(\w)/g, (_, letter) => letter.toUpperCase());
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const cases = [];
const lines = [];
for (const name of icons) {
  const { __iconData } = await import(
    resolve(root, `node_modules/lucide-react/dist/esm/icons/${name}.mjs`)
  );
  const paths = __iconData.node.map(([shape, attributes]) => {
    if (!shapes[shape]) throw new Error(`${name}: unsupported <${shape}>`);
    return `"${shapes[shape](attributes)}"`;
  });
  const key = camel(name);
  cases.push(`    case ${key} = "${name}"`);
  lines.push(`        case .${key}: return [${paths.join(', ')}]`);
}
const source = `// Generated by generate-icons.mjs from lucide (ISC license), the icon set used on web and desktop.
// Do not edit by hand.
enum Lucide: String, CaseIterable {
${cases.join('\n')}

    /// SVG path data in lucide's 24×24 coordinate space, drawn with a 2-unit round stroke.
    var paths: [String] {
        switch self {
${lines.join('\n')}
        }
    }
}
`;
await writeFile(resolve(root, 'apps/ios/Harbor0/Lucide.swift'), source);
console.log(`Wrote ${icons.length} icons.`);
