/* global console */
// Regenerates Icons.kt from the lucide icons the web and desktop apps use.
// Run from the repository root: node apps/android/generate-icons.mjs
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const icons = [
  'archive',
  'arrow-left',
  'arrow-up-from-line',
  'check',
  'chevron-right',
  'circle-alert',
  'circle-check',
  'download',
  'ellipsis-vertical',
  'external-link',
  'file',
  'file-image',
  'file-text',
  'folder',
  'folder-plus',
  'hard-drive',
  'rotate-ccw-clock',
  'laptop',
  'log-out',
  'pencil',
  'plus',
  'refresh-cw',
  'rotate-ccw',
  'settings',
  'share-2',
  'shield-check',
  'trash',
  'wifi-off',
  'x',
];
const n = (value) => Number(value ?? 0);
const shapes = {
  path: (a) => a.d,
  line: (a) => `M${a.x1} ${a.y1}L${a.x2} ${a.y2}`,
  polyline: (a) => `M${a.points}`,
  polygon: (a) => `M${a.points}z`,
  circle: (a) => {
    const r = n(a.r);
    return `M${n(a.cx) - r} ${a.cy}a${r} ${r} 0 1 0 ${2 * r} 0a${r} ${r} 0 1 0 ${-2 * r} 0z`;
  },
  ellipse: (a) =>
    `M${n(a.cx) - n(a.rx)} ${a.cy}a${a.rx} ${a.ry} 0 1 0 ${2 * n(a.rx)} 0a${a.rx} ${a.ry} 0 1 0 ${-2 * n(a.rx)} 0z`,
  rect: (a) => {
    const [x, y, w, h] = [n(a.x), n(a.y), n(a.width), n(a.height)];
    const r = Math.min(n(a.rx ?? a.ry), w / 2, h / 2);
    if (!r) return `M${x} ${y}h${w}v${h}h${-w}z`;
    return `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}v${h - 2 * r}a${r} ${r} 0 0 1 ${-r} ${r}h${2 * r - w}a${r} ${r} 0 0 1 ${-r} ${-r}v${2 * r - h}a${r} ${r} 0 0 1 ${r} ${-r}z`;
  },
};
const pascal = (name) => name.replace(/(^|-)(\w)/g, (_, _dash, letter) => letter.toUpperCase());
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const lines = [];
for (const name of icons) {
  const { __iconData } = await import(
    resolve(root, `node_modules/lucide-react/dist/esm/icons/${name}.mjs`)
  );
  const paths = __iconData.node.map(([shape, attributes]) => {
    if (!shapes[shape]) throw new Error(`${name}: unsupported <${shape}>`);
    return `"${shapes[shape](attributes)}"`;
  });
  lines.push(`    val ${pascal(name)} by lazy { lucide("${name}", ${paths.join(', ')}) }`);
}
const source = `package app.harbor0.android

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

// Generated by generate-icons.mjs from lucide (ISC license), the icon set used on web and desktop.
private fun lucide(name: String, vararg paths: String) = ImageVector.Builder(name, 24.dp, 24.dp, 24f, 24f).apply {
    paths.forEach { addPath(addPathNodes(it), stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) }
}.build()
object Lucide {
${lines.join('\n')}
}
`;
await writeFile(resolve(root, 'apps/android/app/src/main/java/app/harbor0/android/Icons.kt'), source);
console.log(`Wrote ${icons.length} icons.`);
